Avoid using qrexec-client for VM ⇒ VM calls
QubesOS/qubes-core-qrexec pull request #136
Opened 2024-02-10 19:47 UTC by DemiMarie

This saves an `execve()`.  It also allows qrexec-daemon to change how it performs a VM -> VM service call without having to change qrexec-client.  During an upgrade, it is possible that qrexec-daemon is newer than qrexec-client, causing the new qrexec-daemon to try to use a calling convention that the old qrexec-client doesn't support.  Doing VM -> VM calls without calling execve() means this cannot happen.  VM -> dom0 and dom0 -> VM calls still use qrexec-client, but VM -> dom0 calls are safe from domain name reuse races as of 654635c2a374272f18bdfe59472a8ae6b51a551e, and the latter do not involve qrexec-daemon at all.

The preceding commits are all either cleanups or bug fixes.

2024-03-16 03:55 UTC, marmarek requested changes

2024-03-29 15:42 UTC, marmarek commented
Please take a look at test coverage and verify that correct code is used. I'd expected functions like `handle_agent_handshake()`, `select_loop()` or `run_qrexec_to_dom0()` to be covered by tests already.

2024-03-29 19:45 UTC, DemiMarie commented
Culprit is missing `__gcov_flush()` calls.

> Please take a look at test coverage and verify that correct code is used. I'd expected functions like `handle_agent_handshake()`, `select_loop()` or `run_qrexec_to_dom0()` to be covered by tests already.

I added `abort()` calls at the start of these functions and the tests fail as expected.

2024-04-03 21:46 UTC, marmarek commented
This needs a rebase...

2024-04-03 21:48 UTC, DemiMarie commented
…which I was already working on.

2024-04-05 01:09 UTC, marmarek commented
> During an upgrade, it is possible that qrexec-daemon is newer than
qrexec-client, causing the new qrexec-daemon to try to use a calling
convention that the old qrexec-client doesn't support.

I think you meant the other way around (newer qrexec-client)

2024-04-05 01:46 UTC, DemiMarie commented
> > During an upgrade, it is possible that qrexec-daemon is newer than
> > qrexec-client, causing the new qrexec-daemon to try to use a calling
> > convention that the old qrexec-client doesn't support.
> 
> I think you meant the other way around (newer qrexec-client)

I probably meant what I wrote, but what I meant was incorrect.  Will fix.

2024-04-05 02:59 UTC, marmarek requested changes
Besides a comment below, please test old qrexec-daemon + new qrexec-client still works (update dom0 package while some VM is running, and then make call to dom0 from that VM). I don't see any issue for this case, but better double check.

2024-04-05 02:59 UTC, marmarek commented on daemon/qrexec-daemon-common.c
> +    s = connect_unix_socket_by_id(src_domain_id);
Missing error handling

2024-04-05 22:15 UTC, DemiMarie commented on daemon/qrexec-daemon-common.c
> +    s = connect_unix_socket_by_id(src_domain_id);
Fixed.

2024-04-05 22:21 UTC, DemiMarie commented
> Besides a comment below, please test old qrexec-daemon + new qrexec-client still works (update dom0 package while some VM is running, and then make call to dom0 from that VM). I don't see any issue for this case, but better double check.

Tested with VM ⇒ dom0, VM ⇒ VM, and dom0 ⇒ VM service calls, both before and after the change.  All work fine, both with new and existing qrexec-daemon instances.

2024-04-08 21:49 UTC, marmarek approved these changes

2024-04-10 20:22 UTC, DemiMarie commented
All but the last commit is safe to merge.  The last commit has a problem: if there are certain errors (such as `fork()` failing, which can happen!), the socket will be deleted.  I’ll fix this.

2024-04-11 01:58 UTC, DemiMarie commented
This sort of breaks the tests: the test suite passes (at least on my machine), but qrexec-client is only used to _test_ calls to dom0, not to actually execute them.  Most of the code (`run_qrexec_to_dom0()`) is shared between qrexec-daemon and qrexec-client, though.

2024-04-12 02:13 UTC, marmarek commented
> @DemiMarie
[Avoid using alarm(2) for timeouts](https://github.com/QubesOS/qubes-core-qrexec/pull/136/commits/8bea1f179df1c92f0d2a8fa034f92e4b53b8abf1)

Please, don't put new changes into already approved PR. Move it to another PR.

And also, prefer short commit ids for "Fixes" tag (try to keep commit messages not too wide).

2024-04-12 02:16 UTC, DemiMarie commented
> > @DemiMarie
> > [Avoid using alarm(2) for timeouts](https://github.com/QubesOS/qubes-core-qrexec/pull/136/commits/8bea1f179df1c92f0d2a8fa034f92e4b53b8abf1)
> 
> Please, don't put new changes into already approved PR. Move it to another PR.

Sorry, I thought this PR was no longer approved because I had to force-push it to fix a bug.  I will drop this patch and make a separate PR on top of this one.  (If it is separate, merge conflicts galore.)

> And also, prefer short commit ids for "Fixes" tag (try to keep commit messages not too wide).

Sure.

2024-04-13 13:57 UTC, marmarek approved these changes

2024-04-13 21:17 UTC, merged