TCP connection support
QubesOS/qubes-core-qrexec pull request #140
Opened 2024-04-10 00:47 UTC by DemiMarie

Only IP addresses are supported.

2024-04-10 02:03 UTC, marmarek commented
Test test_connect_socket_tcp_ipv6 fail:
```
family = <AddressFamily.AF_INET6: 10>, service = 'qubes.SocketService+++1+65532'
host = '::1', port = 65532, accept = True
    def _test_tcp_raw(self, family: int, service: str, host: str, port: int, accept=True):
        server = socket.socket(family, socket.SOCK_STREAM, socket.IPPROTO_TCP)
        server.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
>       server.bind((host, port))
E       OSError: [Errno 99] Cannot assign requested address
```

2024-04-10 02:06 UTC, DemiMarie commented
> Test test_connect_socket_tcp_ipv6 fail:
> 
> ```
> family = <AddressFamily.AF_INET6: 10>, service = 'qubes.SocketService+++1+65532'
> host = '::1', port = 65532, accept = True
>     def _test_tcp_raw(self, family: int, service: str, host: str, port: int, accept=True):
>         server = socket.socket(family, socket.SOCK_STREAM, socket.IPPROTO_TCP)
>         server.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
> >       server.bind((host, port))
> E       OSError: [Errno 99] Cannot assign requested address
> ```

Is CI misconfigured?  The test definitely passes locally.

2024-04-10 02:06 UTC, DemiMarie commented
Of course, I can skip this test, but I would prefer to fix this in CI.

2024-04-12 01:32 UTC, DemiMarie commented
> Test test_connect_socket_tcp_ipv6 fail:
> 
> ```
> family = <AddressFamily.AF_INET6: 10>, service = 'qubes.SocketService+++1+65532'
> host = '::1', port = 65532, accept = True
>     def _test_tcp_raw(self, family: int, service: str, host: str, port: int, accept=True):
>         server = socket.socket(family, socket.SOCK_STREAM, socket.IPPROTO_TCP)
>         server.setsockopt(socket.SOL_SOCKET, socket.SO_REUSEADDR, 1)
> >       server.bind((host, port))
> E       OSError: [Errno 99] Cannot assign requested address
> ```

This is probably a Docker bug: <https://github.com/moby/moby/issues/33099>.  I suggest either switching to system-wide Podman, or upgrading to a version of Docker that isn’t affected (assuming such a version exists).

2024-04-18 03:37 UTC, marmarek commented
Now this needs a rebase...

2024-04-18 04:32 UTC, DemiMarie commented
> Now this needs a rebase...

fixed

2024-04-18 12:35 UTC, marmarek commented
testing didn't went too far, failed already at qubes-dom0-update (after installing updated qrexec):
```
2024-04-18 07:57:16.171 qrexec-client[4351]: exec.c:601:find_qrexec_service: Service not found: qubes.ReceiveUpdates+
2024-04-18 07:57:16.235 qrexec-client[4351]: qrexec-daemon-common.c:295:handle_failed_exec: failed to spawn process, exiting
2024-04-18 07:57:16.236 qrexec-daemon[2395]: qrexec-daemon.c:733:reap_children: qrexec-policy-exec for connection SOCKET14 exited with code 127, but the response (allow) was already sent
```

`/etc/qubes-rpc/qubes.ReceiveUpdates` is a symlink to executable.

2024-04-18 19:16 UTC, DemiMarie commented
> testing didn't went too far, failed already at qubes-dom0-update (after installing updated qrexec):
> 
> ```
> 2024-04-18 07:57:16.171 qrexec-client[4351]: exec.c:601:find_qrexec_service: Service not found: qubes.ReceiveUpdates+
> 2024-04-18 07:57:16.235 qrexec-client[4351]: qrexec-daemon-common.c:295:handle_failed_exec: failed to spawn process, exiting
> 2024-04-18 07:57:16.236 qrexec-daemon[2395]: qrexec-daemon.c:733:reap_children: qrexec-policy-exec for connection SOCKET14 exited with code 127, but the response (allow) was already sent
> ```
> 
> `/etc/qubes-rpc/qubes.ReceiveUpdates` is a symlink to executable.

Whoops, that means there is a missing unit test.  Will fix.

2024-04-22 03:07 UTC, marmarek requested changes

2024-04-23 15:55 UTC, marmarek requested changes

2024-04-23 15:55 UTC, marmarek commented on qrexec/tests/socket/agent.py
> +        target, dom0 = self.execute_qubesrpc("qubes.SocketService+127.0.0.1", "domX")
```suggestion
        target, dom0 = self.execute_qubesrpc("qubes.SocketService+", "domX")
```
?

2024-04-25 02:30 UTC, marmarek approved these changes

2024-04-25 04:14 UTC, merged