Document rpc-config until skip-service-descriptor
QubesOS/qubes-core-qrexec pull request #153
Opened 2024-04-30 09:23 UTC by ben-grande

Fixes: https://github.com/QubesOS/qubes-issues/issues/9036

See comment https://github.com/QubesOS/qubes-issues/issues/9036#issuecomment-2083760576

2024-05-01 21:26 UTC, marmarek requested changes

2024-05-01 21:26 UTC, marmarek commented on qubes-rpc-config/README
> +  Accepted values: true (default), false, 0 and 1 accepted for backwards
The default is "false".
(I guess got this from `qvm-run`, which by default uses a service that has `wait-for-session=true` set)

2024-05-01 21:26 UTC, marmarek commented on qubes-rpc-config/README
> +  the service. Controlled by the RPC service qubes.WaitForSession. There is
"Controlled" is a weird word for this, maybe "Implemented" or "Performed"?

2024-05-01 21:26 UTC, marmarek commented on qubes-rpc-config/README
> +* skip-service-descriptor: Skip sending service descriptor and go for the
Maybe worth adding a link to https://www.qubes-os.org/doc/qrexec-socket-services/ for explanation what the service descriptor is?

2024-05-01 21:26 UTC, marmarek commented on qubes-rpc-config/README
> +  services, thus the service must be a socket, not an executable.
I'd say "thus the option is valid only for a socket services, not an executable"

2024-05-02 08:28 UTC, ben-grande commented
I understand it is not markdown, but it is easier to read if there are bulleted lists, of which, I followed [Google's markdown guide for nested-list-spacing](https://google.github.io/styleguide/docguide/style.html#nested-list-spacing).

Changes requested above were resolved.

2024-05-02 18:04 UTC, DemiMarie requested changes

2024-05-02 18:04 UTC, DemiMarie commented on qubes-rpc-config/README
> +    options "wait-for-session" and "skip-service-descriptor" accepts the
Only `wait-for-session` accepts it.  `skips-service-descriptor` does not.

2024-05-02 18:04 UTC, DemiMarie commented on qubes-rpc-config/README
> +    *   Accepted values: true, false, 0, 1.
```suggestion
    *   Accepted values: true, false.
```

2024-05-02 18:04 UTC, DemiMarie commented on qubes-rpc-config/README
> +        started.
```suggestion
        started. It is possible for the service to be started even
        if qubes.WaitForSession fails, so the service must not depend on
        wait-for-session=true for security.
```

2024-05-02 19:11 UTC, ben-grande commented on qubes-rpc-config/README
> +* String values: must be enclosed by single quotes "'", e.g. 'str'.
Can we instead document which characters are supported? Or is it easier to say what is not supported? Pushing a commit with your suggestion for now.

2024-05-09 00:31 UTC, marmarek approved these changes

2024-05-09 01:04 UTC, merged