Switch from ‘select’ to ‘poll’
QubesOS/qubes-core-qrexec pull request #79
Opened 2021-08-06 19:05 UTC by DemiMarie

This avoids select()’s FD_SETSIZE limit.

2021-08-06 19:16 UTC, DemiMarie commented
Marked as a draft because it has not been tested.  I should really switch to `epoll`, which would be a performance win.

2022-10-19 22:42 UTC, marmarek commented
Some of the unit tests fail with: `2022-10-19 20:43:16.120 qrexec-client[803]: qrexec-client.c:481:wait_for_vchan_client_with_timeout: vchan connection timeout`

2022-10-20 21:22 UTC, DemiMarie commented
PipelineRetryFailed

2022-10-20 22:13 UTC, marmarek requested changes

2022-10-21 20:39 UTC, DemiMarie commented
PipelineRetryFailed

2022-10-22 23:33 UTC, DemiMarie commented
PipelineRetry

2022-12-19 00:03 UTC, marmarek requested changes

2022-12-19 00:03 UTC, marmarek commented on daemon/qrexec-client.c
> +                timeout_tp.tv_nsec = end_tp.tv_nsec - end_tp.tv_nsec;
```suggestion
                timeout_tp.tv_nsec = end_tp.tv_nsec - now_tp.tv_nsec;
```

2022-12-20 02:38 UTC, marmarek approved these changes

2022-12-26 18:01 UTC, merged