Add a new get_files method to policy admin api
QubesOS/qubes-core-qrexec pull request #94
Opened 2022-07-05 21:15 UTC by marmarta

Needed for global configuration tool.
Also removed requirement for root for performing policy queries, added str representation for policy rules and renamed TestPolicyLoaders to StringPolicyLoaders to be able to use them more flexibly.

2022-07-08 15:47 UTC, marmarek requested changes

2022-07-08 15:47 UTC, marmarek commented on qrexec/policy/admin.py
> +        return ("\n".join(file_list) + "\n").encode('utf-8')
```suggestion
        return ("".join("{}\n".format(f) for f in file_list)).encode('utf-8')
```
Otherwise empty list will have extra `\n`

2022-07-13 01:35 UTC, marmarek approved these changes

2022-07-29 12:01 UTC, marmarta commented
Added a small fix for empty get_files list.

2022-09-17 15:13 UTC, marmarek commented
PipelineRetry

2022-10-11 16:52 UTC, merged